"""empty message

Revision ID: 4ffd5f98d41e
Revises: None
Create Date: 2016-08-16 19:32:24.420254

"""

# revision identifiers, used by Alembic.
revision = '4ffd5f98d41e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_repo',
    sa.Column('full_name', sa.String(length=400), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('lang', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('gmt_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('full_name')
    )
    op.create_table('github_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=400), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('keyword', sa.String(length=200), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('lang', sa.String(length=20), nullable=True),
    sa.Column('snippet', sa.String(length=2000), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=False),
    sa.Column('gmt_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['full_name'], ['github_repo.full_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uk_full_name_file_path_idx', 'github_record', ['full_name', 'file_path'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uk_full_name_file_path_idx', table_name='github_record')
    op.drop_table('github_record')
    op.drop_table('github_repo')
    ### end Alembic commands ###
