"""empty message

Revision ID: 9e518b869c27
Revises: 3b8b4727a0e3
Create Date: 2016-08-18 17:35:51.183172

"""

# revision identifiers, used by Alembic.
revision = '9e518b869c27'
down_revision = '3b8b4727a0e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_record', sa.Column('file_name', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_record', 'file_name')
    ### end Alembic commands ###
