"""empty message

Revision ID: 3b8b4727a0e3
Revises: 3ce9cf9a604c
Create Date: 2016-08-18 14:54:38.855685

"""

# revision identifiers, used by Alembic.
revision = '3b8b4727a0e3'
down_revision = '3ce9cf9a604c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_record', sa.Column('avatar', sa.String(length=2000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_record', 'avatar')
    ### end Alembic commands ###
