"""empty message

Revision ID: 94f6b9439876
Revises: 9e518b869c27
Create Date: 2016-09-21 15:38:17.763518

"""

# revision identifiers, used by Alembic.
revision = '94f6b9439876'
down_revision = '9e518b869c27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocal', sa.String(length=20), nullable=False),
    sa.Column('ip', sa.String(length=39), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('anon', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.Column('gmt_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uk_ip_idx', 'proxy', ['ip', 'port'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uk_ip_idx', table_name='proxy')
    op.drop_table('proxy')
    ### end Alembic commands ###
